#pragma once
#define WINDOW_DIMENSION 900.f

#define NUMBER_OF_INPUTS 48u
#define NUMBER_OF_OUTPUTS 4u

#define BOARD_WIDTH 8
#define BOARD_HEIGHT 8

#define NUMBER_OF_GAMES 100u
#define NUMBER_OF_MOVES_PER_GAME (BOARD_WIDTH * BOARD_WIDTH * BOARD_WIDTH * BOARD_WIDTH)
#define POPULATION 1000u

#define MUTATION_PROBABILITY 0.1f

#define ENABLE_GRAPHICS false
#define RECORD_NEURONS_AND_WEIGHTS true
#define PARALLELIZE true