#pragma once
#define WINDOW_DIMENSION 900.f

#define NUMBER_OF_INPUTS 48u
#define NUMBER_OF_OUTPUTS 4u

#define BOARD_WIDTH  8
#define BOARD_HEIGHT  8

#define NUMBER_OF_GAMES 50u
#define POPULATION 40u

#define MUTATION_PROBABILITY 0.1f